services:
  mdv_app:
    build:
     context: .
     dockerfile: Dockerfile  # Ensure this points to your Dockerfile
    # image: jayeshire/mdv-frontend:latest
    ports:
      - "5055:5055"
      - "5170:5170"
    volumes:
      # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      - .:/app
      - /app/venv/
      - /app/node_modules/
      - ~/mdv:/app/mdv
      - ./app_logs:/app/logs
      # - ~/data:/app/data # thinking about allowing symlinked data folder...
    environment:
      - FLASK_ENV=production  # Set environment to production
      - PYTHONUNBUFFERED=1  
      # Hardcoded database connection details
      - DB_USER=my_db_user
      - DB_PASSWORD=my_db_password
      - DB_NAME=my_db_name
      - DB_HOST=mdv_db  # Assuming the db service name is mdv_db, change if necessary
    depends_on:
      - mdv_db

  mdv_db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: my_db_user          # Hardcoded database user
      POSTGRES_PASSWORD: my_db_password    # Hardcoded database password
      POSTGRES_DB: my_db_name              # Hardcoded database name

volumes:
  postgres-data:
  mdv-data: