services:
  mdv_app:
    build:
     context: .
     dockerfile: Dockerfile  # Ensure this points to your Dockerfile
    # image: jayeshire/mdv-frontend:latest
    ports:
      - "5055:5055"
      - "5170:5170"
    volumes:
      - ./python:/app/python
      - mdv-data:/app/mdv
      - ./app_logs:/app/logs
    environment:
      # Flask configuration
      - FLASK_ENV=production  # Set environment to production
      - PYTHONUNBUFFERED=1  

      # Database connection details
      - DB_USER=my_db_user
      - DB_PASSWORD=my_db_password
      - DB_NAME=my_db_name
      - DB_HOST=mdv_db  # Assuming the db service name is mdv_db

      
      # Auth0 configuration
      #LOGIN_REDIRECT_URL="https://bia.cmd.ox.ac.uk/carroll/login_dev"
      - LOGIN_REDIRECT_URL=https://localhost:5055/login_dev
      - ENABLE_AUTH=1  # Set to 0 to disable authentication
      - AUTH0_DOMAIN=dev-gvt7choa0j53kaa1.us.auth0.com
      - AUTH0_CLIENT_ID=Y3qwB7AhV7ZzJjlOb7AkYfbbme7jfNer
      - AUTH0_CALLBACK_URL=http://localhost:5055/callback
      #AUTH0_CALLBACK_URL=http://bia.cmd.ox.ac.uk/carroll/callback
      - AUTH0_AUDIENCE=https://mdv.dev/api

      # JWT configuration for Auth0 (for token validation)
      - AUTH0_PUBLIC_KEY_URI=https://dev-gvt7choa0j53kaa1.us.auth0.com/.well-known/jwks.json  # JWKS URI to get Auth0 public keys for JWT validation

      # Shibboleth configuration
      - SHIBBOLETH_LOGIN_URL=https://bia.cmd.ox.ac.uk/Shibboleth.sso/Login
      - SHIBBOLETH_LOGOUT_URL=https://bia.cmd.ox.ac.uk/Shibboleth.sso/Logout
    depends_on:
      - mdv_db

  mdv_db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: my_db_user          # Hardcoded database user
      POSTGRES_PASSWORD: my_db_password    # Hardcoded database password
      POSTGRES_DB: my_db_name              # Hardcoded database name

volumes:
  postgres-data:
  mdv-data:

secrets:
  auth0_client_secret:
    file: ./secrets/auth0_client_secret.txt