services:
  mdv_app:
    build:
     context: .
    image: jayeshire/mdv:stable
    ports:
      - "5055:5055"
    volumes:
      #- ./python:/app/python
      - mdv-data:/app/mdv
      #- ./app_logs:/app/logs
    env_file:
      - .env  # Load environment variables from the .env file
    depends_on:
      - mdv_db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  mdv_db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env  # Load database credentials from the .env file
    restart: always

volumes:
  postgres-data:
  mdv-data: