services:
  
  frontend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: jayeshire/mdv-frontend:latest
    ports:
      - "5055:5055"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
