services:
  
  frontend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: jayeshire/mdv-frontend:latest
    ports:
      - "5055:5055"
    volumes:
     - mdv-data:/app/mdv 
    depends_on:
      - database
    #environment:
    #  DATABASE_URI: postgresql://admin:password@database:5432/mdvdatabase

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mdvdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  mdv-data:
