services:
  
  mdv_app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: jayeshire/mdv-frontend:latest
    ports:
      - "5055:5055"
    volumes:
     #- ./python:/app/python
     #- ./mdv:/app/mdv
     - mdv-data:/app/mdv 
    depends_on:
      - mdv_db
    secrets:
      - db_user
      - db_password
      - db_name 

  mdv_db:
    image: postgres:latest
    #ports:
    #  - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true

volumes:
  postgres-data:
  mdv-data:
