services:
  mdv_app:
    build:
      context: .
    image: jayeshire/mdv-frontend:latest
    ports:
      - "5055:5055"
    volumes:
      - mdv-data:/root/mdv 
    depends_on:
      - mdv_db
    secrets:
      - db_user
      - db_password
      - db_name 
    deploy:
      restart_policy:
        condition: none  # Prevent restarting on failure 
    networks:
      - app_net

  mdv_db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name
    deploy:
      restart_policy:
        condition: none  # Prevent restarting on failure
    networks:
      - app_net
    

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true

volumes:
  postgres-data:
  mdv-data:

networks:
  app_net:
    driver: overlay