name: Python CI
# Cache bust: $(date +%s) - Force fresh run to clear stale pyright caches
on:
  push:
    branches:
      # FIXME replace this with main after merge to main
      - dev
#      - main
    paths:
      - 'python/**'
  pull_request:
    branches:
      # FIXME replace this with main after merge to main
      - dev
#      - main
    paths:
      - 'python/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    defaults:
      run:
        working-directory: python
    strategy:
      matrix:
        python-version: [ 3.12 ]
        poetry-version: [ 1.7.1 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # cache: 'poetry'  # Temporarily disabled for cache busting

      - run: poetry install --with dev,backend,auth
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - run: make test

  pyright:
    defaults:
      run:
        working-directory: python
    strategy:
      matrix:
        python-version: [3.12]
        pyright-version: [1.1.401]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - run: poetry install --with dev,backend,auth
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      # Clear all potential caches
      - name: Clear caches
        run: |
          rm -rf ~/.cache/pyright
          rm -rf .pyright_cache
          rm -rf ~/.cache/pip
          poetry cache clear . --all

      - uses: jakebailey/pyright-action@v2
        with:
          version: ${{ matrix.pyright-version }}
  # ruff job is disabled for now pending making it run cleanly...
  # ruff:
  #   defaults:
  #     run:
  #       working-directory: python
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: chartboost/ruff-action@v1
  #       with:
  #         args: "check"
  #     - uses: chartboost/ruff-action@v1
  #       with:
  #         args: "format --check"
