name: Python CI
on:
  push:
    branches:
      - main
    paths:
      - 'python/**'
  pull_request:
    branches:
      - main
    paths:
      - 'python/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    defaults:
      run:
        working-directory: python
    strategy:
      matrix:
        python-version: [ 3.12 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.25"
          cache-dependency-glob: "**/uv.lock"

      - run: uv sync --group dev --group backend --group auth --frozen

      - run: make test

  pyright:
    defaults:
      run:
        working-directory: python
    strategy:
      matrix:
        python-version: [3.12]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.25"
          cache-dependency-glob: "**/uv.lock"

      - run: uv sync --group dev --group backend --group auth --frozen
      - run: make type
  # ruff job is disabled for now pending making it run cleanly...
  # ruff:
  #   defaults:
  #     run:
  #       working-directory: python
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: chartboost/ruff-action@v1
  #       with:
  #         args: "check"
  #     - uses: chartboost/ruff-action@v1
  #       with:
  #         args: "format --check"
