name: Python Performance Tests
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      run_performance_tests:
        description: 'Run performance tests'
        required: true
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  performance-tests:
    # Only run if commit message contains [perf-test] or workflow is manually dispatched
    if: |
      (github.event_name == 'push' && contains(github.event.head_commit.message, '[perf-test]')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[perf-test]')) ||
      github.event_name == 'workflow_dispatch'
    defaults:
      run:
        working-directory: python
    strategy:
      matrix:
        python-version: [ 3.12 ]
        poetry-version: [ 1.7.1 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug workflow trigger
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "PR title: ${{ github.event.pull_request.title }}"
          echo "Branch: ${{ github.ref_name }}"

      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - run: poetry install --with dev,backend,auth
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Run performance tests
        run: make test-performance

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-test-results
          path: python/test-results/
          retention-days: 7 